# Generated by Django 6.0.3 on 2026-03-20 11:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('mac_address', models.CharField(help_text='π.χ. AA:BB:CC:DD:EE:FF', max_length=17, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Ένα όνομα, π.χ. 'Μπαταρία Ταράτσας'", max_length=100)),
                ('users', models.ManyToManyField(blank=True, related_name='allowed_devices', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('timestamp', models.DateTimeField(primary_key=True, serialize=False)),
                ('voltage', models.FloatField(verbose_name='Τάση (V)')),
                ('current', models.FloatField(verbose_name='Ρεύμα (A)')),
                ('temperature', models.FloatField(verbose_name='Θερμοκρασία (°C)')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='myapp.device')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
