# Generated by Django 6.0.3 on 2026-03-20 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='SoC',
            field=models.FloatField(blank=True, null=True, verbose_name='State of Charge (%)'),
        ),
        migrations.AddField(
            model_name='measurement',
            name='SoH',
            field=models.FloatField(blank=True, null=True, verbose_name='State of Health (%)'),
        ),
    ]
