# Generated by Django 6.0.3 on 2026-03-28 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_measurement_soc_measurement_soh'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurement',
            old_name='SoC',
            new_name='soc',
        ),
        migrations.RenameField(
            model_name='measurement',
            old_name='SoH',
            new_name='soh',
        ),
    ]
