# Generated by Django 6.0.3 on 2026-05-06 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_soc_measurement_soc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='power',
            field=models.FloatField(blank=True, null=True, verbose_name='Ισχύς (W)'),
        ),
    ]
